travis:
  secure:
    BINSTAR_TOKEN: JfXmdl/nZGOXueumpjVA/sjYyNLbtbGEWaNJMwUlaTu8aOgfcUGT1DHo2nxX2IBPgsWw1muZArGSw+GpQocsJAZbCWLxXjNI0aqnW7XJLjuSfNA97EhMDUDRebXmQpwkeO4eGTa0yH7S/xpi3dEOJLEB/skgXwR5bH56y0ZcuIYODJ4YRZzbCCUa+YcwiOQihtT/JAzzVDeaF9H4QYmUgsuCyA8VhnvhAQFukwJYyf2cjvKcoVaCjdYCfZWtOHks9wzVkzpySBu3EU+sKkaYEknZo7LcF6BCs+C3kd+6tUUdmZqUQfbyMcS67xAcyYW1vU4RWIJan1WHBEe9uZs3GNJcCpxRmd/00W840P7oZa7brS9wm9s5fteh45+cbJ2U+GJB6rDI0hbhIwDMYznT9G3noT9uE9+BNL7FPeQ6gIpNQ76ZP1f31EdR1ncvxqzaffcArEXcCKnRO3S6ab5YcxQqaopMLDojwryBehvz3Sq4O+NhDhr0eaHi14wOkh6ewy2ZkTYM7LHX9Knw03INWaJsRes/JaegKw6xkZ7bz7oykL2Mt729WdYxh3so5N2+tV32sCy9ktpYX4S30bCJ1/3g2qihu/YJxVnYrhNc/UaJkEBHq8+9CaCwwCX7z1C+uYxCeVUAtW9j61W9ZKdQtXnasCDrFt66omIAJrxa9SU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
